variables:
  EXTRA_DNF_REPOS: |
                   [KylinSec_3.5.2_Customize_Kiran2.7]
                   name=Kiran2.7(standard_x86_64)
                   type=rpm-md
                   baseurl=http://build.kylinsec.com.cn:82/KylinSec:/3.5.2:/Customize:/Kiran2.7/standard_x86_64/
                   gpgcheck=1
                   gpgkey=http://build.kylinsec.com.cn:82/KylinSec:/3.5.2:/Customize:/Kiran2.7/standard_x86_64/repodata/repomd.xml.key
                   enabled=1
  RPM_BUILD_REQUIRES: 'gcc-c++ cmake pkgconf qt5-qtbase-devel qt5-qtbase-private-devel qt5-qtbase-static qt5-qtsvg-devel qt5-linguist gsettings-qt-devel kiran-qdbusxml2cpp kiran-log-qt5-devel kiran-cc-daemon-devel'
  DEFAULT_IMAGE: kylinsec-3.5.2
include:
  - project: 'os/ks-devops'
    ref: main
    file: '/entrypoint/develop/cmake.yml'
