include(GNUInstallDirs)

find_package(PkgConfig REQUIRED)

# 通过qt5的pkgconfig配置文件取出插件安装位置、插件共享库安装位置
pkg_search_module(Qt5 REQUIRED Qt5)
pkg_get_variable(QT5_PLUGIN_DIR Qt5 plugindir)

# 安装路径变量
set(QT5_PLATFORM_THEME_INSTALL_DIR ${QT5_PLUGIN_DIR}/platformthemes/)
set(QT5_STYLE_INSTALL_DIR ${QT5_PLUGIN_DIR}/styles)

set(KQI_INSTALL_INCLUDEDIR ${CMAKE_INSTALL_FULL_INCLUDEDIR}/${PROJECT_NAME})
set(KQI_INSTALL_DATADIR ${CMAKE_INSTALL_FULL_DATADIR}/${PROJECT_NAME})
set(KQI_INSTALL_TRANSLATIONDIR ${KQI_INSTALL_DATADIR}/translations)
set(KQI_INSTALL_SYSCONFDIR ${CMAKE_INSTALL_FULL_SYSCONFDIR}/${PROJECT_NAME})
